<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-10-30T04:32:56 PDT" name="Suite" finished-at="2021-10-30T04:33:43 PDT" duration-ms="47371">
    <groups>
    </groups>
    <test started-at="2021-10-30T04:32:56 PDT" name="ChromeTest" finished-at="2021-10-30T04:33:43 PDT" duration-ms="47371">
      <class name="TestClass2.TestClassTestNGHomefb">
        <test-method is-config="true" signature="beforeTest(java.lang.String)[pri:0, instance:TestClass2.TestClassTestNGHomefb@4ac3c60d]" started-at="2021-10-30T04:32:56 PDT" name="beforeTest" finished-at="2021-10-30T04:33:10 PDT" duration-ms="13754" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:TestClass2.TestClassTestNGHomefb@4ac3c60d]" started-at="2021-10-30T04:33:10 PDT" name="beforeClass" finished-at="2021-10-30T04:33:10 PDT" duration-ms="30" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="beforemethod()[pri:0, instance:TestClass2.TestClassTestNGHomefb@4ac3c60d]" started-at="2021-10-30T04:33:10 PDT" name="beforemethod" finished-at="2021-10-30T04:33:10 PDT" duration-ms="450" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforemethod -->
        <test-method signature="testA()[pri:0, instance:TestClass2.TestClassTestNGHomefb@4ac3c60d]" started-at="2021-10-30T04:33:10 PDT" name="testA" finished-at="2021-10-30T04:33:40 PDT" duration-ms="29602" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.facebook.com/groups/ed/] but found [https://www.facebook.com/groups/feed/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.facebook.com/groups/ed/] but found [https://www.facebook.com/groups/feed/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestClass2.TestClassTestNGHomefb.testA(TestClassTestNGHomefb.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA -->
        <test-method is-config="true" signature="aftermethod(org.testng.ITestResult)[pri:0, instance:TestClass2.TestClassTestNGHomefb@4ac3c60d]" started-at="2021-10-30T04:33:40 PDT" name="aftermethod" finished-at="2021-10-30T04:33:43 PDT" duration-ms="3471" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testA status=FAILURE method=TestClassTestNGHomefb.testA()[pri:0, instance:TestClass2.TestClassTestNGHomefb@4ac3c60d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- aftermethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:TestClass2.TestClassTestNGHomefb@4ac3c60d]" started-at="2021-10-30T04:33:43 PDT" name="afterClass" finished-at="2021-10-30T04:33:43 PDT" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- TestClass2.TestClassTestNGHomefb -->
    </test> <!-- ChromeTest -->
  </suite> <!-- Suite -->
</testng-results>
